#!/usr/bin/env bash
# Finalize step: after the continuous curve finishes (all 205-220 results exist),
#  1. patch builder rows with real metrics (backfill_results.py)
#  2. run the Excel builder (regenerates all Excels + configs)
#  3. restore the correct custom configs for 197-220 (mechanism params + bias 0.0)
#  4. flip status=completed on 205-220 configs
set -e
cd "$(dirname "$0")"

echo "=== [1/4] Patch builder rows with real metrics ==="
/home/lumin/miniconda3/bin/python backfill_results.py

echo "=== [2/4] Run Excel builder ==="
# The builder imports from the additive submodule; run with repo root as cwd.
# Use PYTHONPATH so `from build_unified_single_sheet import ...` resolves.
PYTHONPATH="$PWD" /home/lumin/miniconda3/bin/python expand_and_update_all_excels.py

echo "=== [3/4] Restore correct configs from backup ==="
CFG=additive-rand-transformer/configs
# The builder regenerates all configs from rows (losing mechanism params and
# using bias 0.5); restore our backed-up configs (mechanism params + bias 0.0).
rm -rf "$CFG"
mkdir -p "$CFG"
cp config_backup/*.json "$CFG/"
echo "restored $(ls $CFG/*.json | wc -l) configs from config_backup/"
# maze configs also regenerated by builder — restore from backup
MCFG=maze-transformer/configs
rm -rf "$MCFG"
mkdir -p "$MCFG"
cp config_backup/maze/*.json "$MCFG/"
echo "restored $(ls $MCFG/*.json | wc -l) maze configs"

echo "=== [4/4] Flip 197-220 configs to completed ==="
export PATH="/home/lumin/miniconda3/bin:$PATH"
python3 - <<'EOF'
import json, glob, os
cfg_dir = 'additive-rand-transformer/configs'
for seq in range(205, 221):
    matches = glob.glob(os.path.join(cfg_dir, f'{seq}_*.json'))
    if not matches:
        print(f'  [warn] no config for {seq}')
        continue
    for p in matches:
        c = json.load(open(p))
        c['status'] = 'completed'
        json.dump(c, open(p, 'w'), ensure_ascii=False, indent=2)
print('step configs 205-220 marked completed')
EOF

echo "=== done ==="
