"""
JsonPayloadSender - 动态 JSON Payload 构造与发送器

【设计目标】
- 分离 Payload 构造逻辑与底层 HTTP 传输，通过组合 JsonApiRequester 实现复用
- 支持双模式消息组装：Context 模式（外部文件）与 Payload 模式（本地预设）
- 提供字段级持久化能力，便于运行时动态调整参数（temperature、model 等）
- 内部字段隔离：以下划线开头的字段为控制元数据，不进入最终请求体

【典型调用链】
    JsonPayloadSender ──→ send_request_with_messages(dynamic_msgs, use_context)
                              │
                    ┌────────┴────────┐
                    ↓                 ↓
                use_context=False   use_context=True
                [Payload 模式]       [Context 模式]
                    │                 │
            payload.json["messages"]  payload.json["_context"] ──→ 外部文件
                    │                 │
                    └────────┬────────┘
                             ↓
                    base_messages + dynamic_messages
                             │
                    清理 _* 字段 ──→ requester.send_request()

【文件格式示例】
payload.json:
    {
        "model": "gpt-4",
        "temperature": 0.7,
        "_context": "./system_prompt.json",  // Context 模式入口
        "messages": [                        // Payload 模式来源
            {"role": "system", "content": "你是助手"}
        ]
    }

system_prompt.json (Context 模式指向的外部文件):
    [
        {"role": "system", "content": "长篇幅系统提示..."},
        {"role": "user", "content": "示例对话..."}
    ]
"""

import os
import json
import copy
from dataclasses import dataclass, field
from typing import List, Optional, Any, Dict, Callable, Union
from pathlib import Path

# 类型前向声明，避免循环导入
from typing import TYPE_CHECKING
if TYPE_CHECKING:
    from json_api_requester import JsonApiRequester, RequestContext


@dataclass
class SendResult:
    """
    【用途】send_request_with_messages 的完整结果封装
    
    【字段说明】
        success: 请求是否成功到达 API（非业务成功，HTTP 层成功）
        response: 原始 Response 对象（需调用方关闭）或 None
        final_payload: 实际发送的请求体（清理后，用于审计/调试）
        base_message_count: 来自文件的基础消息数
        dynamic_message_count: 传入的动态消息数
        error_info: 失败时的结构化错误信息
    """
    success: bool
    response: Optional[Any]  # requests.Response 或 None
    final_payload: Dict[str, Any]
    base_message_count: int = 0
    dynamic_message_count: int = 0
    error_info: Optional[str] = None


class JsonPayloadSender:
    """
    【使用上下文】
    业务层 Payload 组装类，专注消息构造与文件管理，不直接处理网络 I/O。
    
    【核心设计决策】
    1. 组合优于继承：持有 JsonApiRequester 实例，而非继承，保持职责分离
    
    2. 双模式策略：
       - Payload 模式：快速原型，所有配置在单一文件
       - Context 模式：生产环境，系统提示/示例对话分离，支持热更新
    
    3. 字段命名空间隔离：
       _context, _template 等内部控制字段自动过滤，防止误入 API 请求
    
    4. 原子化文件操作：
       读写使用临时文件+重命名，避免半写状态损坏配置
    
    5. 防御性拷贝：
       所有返回/发送的 Payload 均为深拷贝，防止调用方修改影响内部状态
    """

    def __init__(
        self,
        requester: 'JsonApiRequester',
        payload_file_path: str = "payload.json",
        *,
        auto_create_payload: bool = True,
        default_payload: Optional[Dict[str, Any]] = None,
        on_payload_change: Optional[Callable[[str, Any, Dict], None]] = None,
    ):
        """
        【调用效果】
        绑定 Requester 实例，初始化 payload 文件路径，可选自动创建默认配置
        
        【调用上下文】
        业务模块初始化时，通常每个对话会话或每个功能模块一个 Sender 实例
        
        【参数说明】
            requester: 已配置好的 JsonApiRequester 实例（网络层）
            payload_file_path: 配置文件路径，支持相对/绝对路径
            auto_create_payload: 文件不存在时是否自动创建（默认 True）
            default_payload: 自动创建时的默认内容（默认含空 messages）
            on_payload_change: 字段变更回调，签名 (key, value, full_payload) -> None
        
        【其他内容】
        路径处理：自动转换为 Path 对象，统一处理 Windows/Unix 路径分隔符
        初始化失败：文件权限问题等将抛出 OSError，需调用方处理
        """
        self._requester: 'JsonApiRequester' = requester
        self._payload_path: Path = Path(payload_file_path).resolve()
        self._on_payload_change: Optional[Callable[[str, Any, Dict], None]] = on_payload_change
        
        # 默认配置模板
        self._default_template: Dict[str, Any] = default_payload or {
            "messages": [],
            "model": "gpt-3.5-turbo",
            "_context": "",
            "_description": "Generated by JsonPayloadSender"
        }
        
        # 确保目录存在
        self._payload_path.parent.mkdir(parents=True, exist_ok=True)
        
        # 自动创建或验证存在性
        if not self._payload_path.exists():
            if auto_create_payload:
                self._atomic_write(self._default_template)
                print(f"[JsonPayloadSender] 自动创建配置: {self._payload_path}")
            else:
                raise FileNotFoundError(f"Payload 文件不存在: {self._payload_path}")
        
        # 缓存最后一次读取的内容（可选优化，减少磁盘 IO）
        self._cache: Optional[Dict[str, Any]] = None
        self._cache_mtime: float = 0.0
        
        print(f"[JsonPayloadSender] 初始化完成 | 路径: {self._payload_path}")

    def _atomic_write(self, data: Dict[str, Any]) -> None:
        """
        【调用效果】
        原子化写入配置，使用临时文件+重命名避免写中断损坏
        
        【调用上下文】
        内部方法，update_payload_field 和初始化时调用
        
        【异常处理】
        写入失败保留原文件，抛出 OSError
        """
        temp_path = self._payload_path.with_suffix('.tmp')
        try:
            with open(temp_path, 'w', encoding='utf-8') as f:
                json.dump(data, f, indent=2, ensure_ascii=False)
                f.flush()
                os.fsync(f.fileno())  # 强制落盘
            
            # 原子替换
            temp_path.replace(self._payload_path)
            
            # 更新缓存
            self._cache = copy.deepcopy(data)
            self._cache_mtime = self._payload_path.stat().st_mtime
            
        except Exception as e:
            # 清理临时文件
            if temp_path.exists():
                temp_path.unlink(missing_ok=True)
            raise OSError(f"配置写入失败: {e}") from e

    def _read_payload(self, force_refresh: bool = False) -> Dict[str, Any]:
        """
        【调用效果】
        读取 payload 文件，带缓存优化和 staleness 检测
        
        【调用上下文】
        所有需要读取配置的内部方法
        
        【缓存策略】
        默认启用 mtime 检测，文件未变更时返回缓存，减少磁盘 IO
        """
        if not force_refresh and self._cache is not None:
            try:
                current_mtime = self._payload_path.stat().st_mtime
                if current_mtime == self._cache_mtime:
                    return copy.deepcopy(self._cache)
            except OSError:
                pass  # 降级到重新读取
        
        try:
            with open(self._payload_path, 'r', encoding='utf-8') as f:
                data = json.load(f)
            
            self._cache = copy.deepcopy(data)
            self._cache_mtime = self._payload_path.stat().st_mtime
            
            return copy.deepcopy(data)
            
        except json.JSONDecodeError as e:
            raise ValueError(f"配置文件 JSON 格式错误: {e}") from e
        except Exception as e:
            raise IOError(f"读取配置文件失败: {e}") from e

    def update_payload_field(self, key: str, value: Any, persist: bool = True) -> Dict[str, Any]:
        """
        【调用效果】
        更新指定字段，可选持久化，返回完整配置快照
        
        【调用上下文】
        运行时动态调整参数，如切换模型、调整 temperature
        
        【参数说明】
            key: 字段名，以下划线开头将被识别为内部字段
            value: 任意可 JSON 序列化的值
            persist: 是否立即写入文件（默认 True）；False 时仅内存修改
        
        【回调触发】
        若设置了 on_payload_change，持久化后同步触发
        
        【返回】
        深拷贝后的完整配置，供调用方确认变更
        
        【其他内容】
        线程安全：非线程安全，多线程环境需外部加锁
        """
        data = self._read_payload()
        old_value = data.get(key)
        data[key] = value
        
        if persist:
            self._atomic_write(data)
            print(f"[JsonPayloadSender] 字段持久化: {key} {old_value!r} -> {value!r}")
            
            if self._on_payload_change:
                try:
                    self._on_payload_change(key, value, copy.deepcopy(data))
                except Exception as e:
                    print(f"[JsonPayloadSender] 变更回调异常: {e}")
        else:
            self._cache = copy.deepcopy(data)
            print(f"[JsonPayloadSender] 字段内存更新: {key} {old_value!r} -> {value!r}")
        
        return copy.deepcopy(data)

    def get_payload_field(self, key: str, default: Any = None) -> Any:
        """
        【调用效果】
        安全获取字段值，支持嵌套路径（如 "model_params.temperature"）
        
        【调用上下文】
        读取配置，替代直接操作文件
        """
        data = self._read_payload()
        
        # 支持点号路径
        keys = key.split('.')
        for k in keys:
            if isinstance(data, dict) and k in data:
                data = data[k]
            else:
                return default
        
        return copy.deepcopy(data)

    def send_request_with_messages(
        self,
        dynamic_messages: List[Dict[str, Any]],
        use_context: bool = False,
        *,
        request_metadata: Optional[Dict[str, Any]] = None,
        request_timeout: Optional[Union[float, tuple]] = None,
    ) -> SendResult:
        """
        【调用效果】
        双模式组装消息，清理内部字段，委托 Requester 发送，返回结构化结果
        
        【调用上下文】
        核心业务调用点，每次用户消息输入时触发
        
        【参数说明】
            dynamic_messages: 动态消息列表，通常为最新用户输入+历史
            use_context: 模式开关
                - False (默认): 从 payload["messages"] 加载基础消息
                - True: 从 payload["_context"] 指向的外部文件加载
            request_metadata: 透传至 Requester 的 context_metadata，用于 trace_id 等
            request_timeout: 覆盖默认的无超时策略，仅当次请求生效
        
        【模式详解】
        
        Payload 模式 (use_context=False):
            base = payload.json["messages"]  # 预设的系统提示、示例对话
            final = base + dynamic_messages  # 追加实时对话
        
        Context 模式 (use_context=True):
            context_path = payload.json["_context"]  # 如 "./prompts/coder.json"
            base = json.load(context_path)           # 热加载外部长提示
            final = base + dynamic_messages
        
        【字段清理】
        最终请求体移除所有以下划线开头的键，包括：
            - _context: 模式控制，非业务数据
            - _template, _version, _description 等自定义元数据
        
        【返回】
        SendResult 结构，包含完整追踪信息，失败时 error_info 说明原因
        
        【其他内容】
        空消息防护：base_messages 和 dynamic_messages 均为空时发出警告但仍执行
        路径安全：Context 模式解析为绝对路径，防止目录遍历攻击
        """
        main_payload = self._read_payload()
        base_messages: List[Dict[str, Any]] = []
        mode_name = "Unknown"

        # ═══════════════════════════════════════════════════════════════════════
        # 模式分支：加载基础消息
        # ═══════════════════════════════════════════════════════════════════════
        
        if use_context:
            mode_name = "Context"
            context_ref = main_payload.get('_context', '')
            
            if not context_ref:
                print(f"[JsonPayloadSender][警告] Context 模式启用但 _context 为空，"
                      f"回退到空基础消息")
            else:
                # 安全路径解析：相对于 payload 文件目录，或绝对路径
                context_path = Path(context_ref)
                if not context_path.is_absolute():
                    context_path = self._payload_path.parent / context_path
                
                context_path = context_path.resolve()
                
                # 安全检查：确保不跳出 payload 所在目录树（可选严格模式）
                # if not str(context_path).startswith(str(self._payload_path.parent)):
                #     raise SecurityError(f"Context 路径越界: {context_path}")
                
                if context_path.exists():
                    raw_content = self._read_external_file(context_path)
                    # 支持两种格式：直接消息列表，或 {"messages": [...]} 包装
                    if isinstance(raw_content, list):
                        base_messages = raw_content
                    elif isinstance(raw_content, dict) and 'messages' in raw_content:
                        base_messages = raw_content['messages']
                    else:
                        print(f"[JsonPayloadSender][警告] Context 文件格式未知，"
                              f"期望列表或 {{messages: [...]}}，实际: {type(raw_content)}")
                else:
                    print(f"[JsonPayloadSender][警告] Context 文件不存在: {context_path}")
            
            print(f"[{mode_name} 模式] 加载外部消息: {len(base_messages)}条 "
                  f"(来源: {context_path if context_ref else 'N/A'})")
        
        else:
            mode_name = "Payload"
            base_messages = main_payload.get("messages", [])
            print(f"[{mode_name} 模式] 加载预设消息: {len(base_messages)}条")

        # ═══════════════════════════════════════════════════════════════════════
        # 组装与清理
        # ═══════════════════════════════════════════════════════════════════════
        
        # 深拷贝避免污染原始配置
        final_payload = copy.deepcopy(main_payload)
        final_payload["messages"] = base_messages + list(dynamic_messages)
        
        # 关键：移除所有内部控制字段（单下划线开头）
        clean_payload = {
            k: v for k, v in final_payload.items() 
            if not k.startswith('_')
        }
        
        # 统计信息
        total_msgs = len(clean_payload.get("messages", []))
        print(f"[{mode_name} 模式] 最终消息数: {total_msgs} "
              f"(基础 {len(base_messages)} + 动态 {len(dynamic_messages)})")

        # ═══════════════════════════════════════════════════════════════════════
        # 委托发送
        # ═══════════════════════════════════════════════════════════════════════
        
        try:
            response = self._requester.send_request(
                clean_payload,
                timeout=request_timeout,
                context_metadata=request_metadata,
            )
            
            success = response is not None
            
            return SendResult(
                success=success,
                response=response,
                final_payload=clean_payload,
                base_message_count=len(base_messages),
                dynamic_message_count=len(dynamic_messages),
                error_info=None if success else "Requester 返回 None（网络/连接失败）"
            )
            
        except Exception as e:
            # 捕获 Requester 抛出的异常（如 Hook 异常）
            print(f"[JsonPayloadSender] 发送异常: {type(e).__name__}: {e}")
            return SendResult(
                success=False,
                response=None,
                final_payload=clean_payload,
                base_message_count=len(base_messages),
                dynamic_message_count=len(dynamic_messages),
                error_info=f"{type(e).__name__}: {str(e)}"
            )

    def _read_external_file(self, path: Path) -> Any:
        """
        【调用效果】
        安全读取外部 JSON 文件，带格式校验
        
        【调用上下文】
        Context 模式专用，内部方法
        """
        try:
            with open(path, 'r', encoding='utf-8') as f:
                return json.load(f)
        except json.JSONDecodeError as e:
            raise ValueError(f"Context 文件 JSON 错误 [{path}]: {e}") from e
        except Exception as e:
            raise IOError(f"读取 Context 文件失败 [{path}]: {e}") from e

    def reload_from_disk(self) -> Dict[str, Any]:
        """
        【调用效果】
        强制刷新缓存，从磁盘重新读取
        
        【调用上下文】
        外部文件变更后（如热更新系统提示），或调试时
        """
        return self._read_payload(force_refresh=True)

    def validate_context_path(self, path: Optional[str] = None) -> tuple[bool, str]:
        """
        【调用效果】
        验证 Context 路径有效性，返回 (是否有效, 诊断信息)
        
        【调用上下文】
        配置检查工具、启动自检、CI/CD 验证
        """
        check_path = path or self.get_payload_field('_context', '')
        if not check_path:
            return False, "_context 字段为空"
        
        ctx_path = Path(check_path)
        if not ctx_path.is_absolute():
            ctx_path = self._payload_path.parent / ctx_path
        
        ctx_path = ctx_path.resolve()
        
        if not ctx_path.exists():
            return False, f"文件不存在: {ctx_path}"
        if not ctx_path.is_file():
            return False, f"路径不是文件: {ctx_path}"
        
        try:
            content = self._read_external_file(ctx_path)
            if isinstance(content, list):
                return True, f"有效列表格式，{len(content)} 条消息"
            elif isinstance(content, dict) and 'messages' in content:
                return True, f"有效对象格式，{len(content['messages'])} 条消息"
            else:
                return False, f"格式不符: 期望列表或 {{messages: [...]}}"
        except Exception as e:
            return False, f"读取失败: {e}"

    def __repr__(self) -> str:
        status = "cached" if self._cache else "uncached"
        return (f"JsonPayloadSender(path={self._payload_path!s}, "
                f"mode={'context' if self.get_payload_field('_context') else 'payload'}, "
                f"status={status})")


# ═══════════════════════════════════════════════════════════════════════════════
# 使用示例
# ═══════════════════════════════════════════════════════════════════════════════

def example_sender_usage():
    """
    【完整调用示例】展示 Payload 模式、Context 模式、动态字段更新
    """
    import tempfile
    import os
    
    # 模拟创建临时配置环境
    temp_dir = Path(tempfile.mkdtemp())
    
    # 创建 payload.json
    payload_path = temp_dir / "payload.json"
    payload_config = {
        "model": "gpt-4",
        "temperature": 0.7,
        "messages": [
            {"role": "system", "content": "你是代码助手"}
        ],
        "_context": str(temp_dir / "system_prompt.json"),
        "_version": "1.0"
    }
    with open(payload_path, 'w') as f:
        json.dump(payload_config, f)
    
    # 创建 Context 外部文件
    context_path = temp_dir / "system_prompt.json"
    context_messages = [
        {"role": "system", "content": "长篇幅系统提示..." * 10},
        {"role": "user", "content": "示例用户输入"},
        {"role": "assistant", "content": "示例助手回复"}
    ]
    with open(context_path, 'w') as f:
        json.dump(context_messages, f)
    
    # 模拟 Requester（实际应导入真实类）
    class MockRequester:
        def __init__(self):
            self.last_metadata = None
        def send_request(self, body, **kwargs):
            print(f"[MockRequester] 收到请求: {len(body.get('messages', []))} 条消息")
            self.last_metadata = kwargs.get('context_metadata')
            # 模拟响应
            class MockResp:
                status_code = 200
            return MockResp()
    
    # ── 初始化 Sender ─────────────────────────────────────────────────────────
    
    def on_change(key, val, full):
        print(f"[回调] {key} 变更为 {val!r}")
    
    requester = MockRequester()
    sender = JsonPayloadSender(
        requester,
        str(payload_path),
        on_payload_change=on_change
    )
    
    print(f"\n初始化状态: {sender!r}")
    
    # ── 场景 1: Payload 模式（默认）────────────────────────────────────────────
    print("\n" + "="*50 + " 场景 1: Payload 模式 " + "="*50)
    
    result = sender.send_request_with_messages([
        {"role": "user", "content": "你好"}
    ])
    print(f"结果: success={result.success}, "
          f"base={result.base_message_count}, "
          f"dynamic={result.dynamic_message_count}")
    print(f"最终请求体含字段: {list(result.final_payload.keys())}")
    # 验证 _version 被清理
    assert '_version' not in result.final_payload
    
    # ── 场景 2: Context 模式 ──────────────────────────────────────────────────
    print("\n" + "="*50 + " 场景 2: Context 模式 " + "="*50)
    
    result = sender.send_request_with_messages(
        dynamic_messages=[{"role": "user", "content": "写个快速排序"}],
        use_context=True,
        request_metadata={"trace_id": "req-123", "user_id": "u-456"}
    )
    print(f"Context 模式结果: {result.base_message_count} 基础 + "
          f"{result.dynamic_message_count} 动态")
    # 验证 metadata 透传
    print(f"透传的 metadata: {requester.last_metadata}")
    
    # ── 场景 3: 动态字段更新 ──────────────────────────────────────────────────
    print("\n" + "="*50 + " 场景 3: 字段更新 " + "="*50)
    
    sender.update_payload_field("temperature", 0.9)
    sender.update_payload_field("_custom_flag", True)  # 内部字段
    print(f"当前 temperature: {sender.get_payload_field('temperature')}")
    print(f"嵌套访问: {sender.get_payload_field('model', 'default-model')}")
    
    # ── 场景 4: 验证工具 ──────────────────────────────────────────────────────
    print("\n" + "="*50 + " 场景 4: 路径验证 " + "="*50)
    
    valid, info = sender.validate_context_path()
    print(f"Context 路径验证: {valid}, {info}")
    
    # ── 清理 ─────────────────────────────────────────────────────────────────
    import shutil
    shutil.rmtree(temp_dir)
    print(f"\n清理临时目录: {temp_dir}")


if __name__ == "__main__":
    example_sender_usage()