"""Membership test: is this expression generated by our specific generator?

The generator has rules that go BEYOND "valid arithmetic":
  * operands are 1..max_digits digit non-negative integers, NO leading zeros
    (except for the number 0 itself)
  * spacing is random in 0..max_spaces around each operator (so BOTH
    "1234+5678=6912" and "1234  +  5678 = 6912" are valid output)
  * for "+": result = a + b (no upper bound; longer operands are allowed)
  * for "-": a >= b so the result is non-negative
  * format is exactly one operator between two operands, then "=" and a result

A model trained on the generator learns this whole distribution. So given ANY
expression, its log-likelihood tells you whether it plausibly came from THIS
generator. We probe this with several families of counter-examples that violate
one specific generator rule each:

  positive          — from the generator (positive control)
  wrong_result      — arithmetic result is wrong
  leading_zero      — "007 + 3 = 10"  (generator never emits leading zeros)
  negative_result   — "5 - 10 = 5"    (generator forbids a < b)
  wrong_operator    — "1234 = 5678 = 6912"  (uses '=' where '+' belongs)

A well-trained model assigns HIGH log-likelihood to `positive` and LOW to all
of the others. The margin is the membership score.
"""

from __future__ import annotations

import random
from typing import Dict, List, Tuple

import torch
import torch.nn.functional as F

from .data import BOS, EOS, PLUS, MINUS, EQ, SP, TOK_TO_ID, decode
from .model import TinyGPT


def _tok(*chars: str) -> List[int]:
    """Map each arg (a full token name) to its id. Digits must come via _int_to_tokens."""
    return [TOK_TO_ID[c] for c in chars]


def make_positive(rng: random.Random) -> List[int]:
    """An expression that the generator would actually produce."""
    from .data import gen_expression
    return gen_expression(rng)


def make_wrong_result(rng: random.Random) -> List[int]:
    """Same shape, but the last result digit is flipped."""
    from .data import gen_expression
    expr = list(gen_expression(rng))
    for i in range(len(expr) - 2, -1, -1):
        if 0 <= expr[i] <= 9:
            expr[i] = (expr[i] + 1) % 10
            break
    return expr


def make_leading_zero(rng: random.Random) -> List[int]:
    """Force a leading zero on the first operand — generator never does this."""
    a = rng.randint(1, 999)
    b = rng.randint(0, 9999)
    op = PLUS if rng.random() < 0.5 else MINUS
    if op == MINUS and a < b:
        a, b = b, a
    c = a + b if op == PLUS else a - b
    a_str = "0" + str(a)          # leading zero — never emitted by the generator
    return (
        _tok("<BOS>")
        + _tok(*a_str)
        + [SP] * rng.randint(0, 3) + [op] + [SP] * rng.randint(0, 3)
        + _tok(*str(b))
        + [SP] * rng.randint(0, 3) + [EQ] + [SP] * rng.randint(0, 3)
        + _tok(*str(c))
        + [EOS]
    )


def make_negative_result(rng: random.Random) -> List[int]:
    """Subtraction where a < b — generator swaps to keep the result non-negative."""
    a = rng.randint(1, 9)
    b = rng.randint(10, 999)
    c = abs(a - b)               # render |a-b| so the expression is well-formed
    return (
        _tok("<BOS>")
        + _tok(*str(a))
        + [SP] * rng.randint(0, 3) + [MINUS] + [SP] * rng.randint(0, 3)
        + _tok(*str(b))
        + [SP] * rng.randint(0, 3) + [EQ] + [SP] * rng.randint(0, 3)
        + _tok(*str(c))
        + [EOS]
    )


def make_wrong_operator(rng: random.Random) -> List[int]:
    """Use '=' where an operator should be — not a generator output."""
    a = rng.randint(1, 9999)
    b = rng.randint(0, 9999)
    c = a + b
    return (
        _tok("<BOS>")
        + _tok(*str(a))
        + [SP] * rng.randint(0, 3) + [EQ] + [SP] * rng.randint(0, 3)
        + _tok(*str(b))
        + [SP] * rng.randint(0, 3) + [EQ] + [SP] * rng.randint(0, 3)
        + _tok(*str(c))
        + [EOS]
    )


# name -> factory. Each factory produces expressions that violate exactly one
# generator rule (except `positive`, which obeys all of them).
FACTORIES = {
    "positive":        make_positive,
    "wrong_result":    make_wrong_result,
    "leading_zero":    make_leading_zero,
    "negative_result": make_negative_result,
    "wrong_operator":  make_wrong_operator,
}


def sequence_logprob(model: TinyGPT, tokens: List[int], device: torch.device) -> Tuple[float, int]:
    """(total_ll, n_predicted) of a token sequence under the model (nats).

    total_ll = sum_i log P(tokens[i+1] | tokens[0..i]) — the standard
    autoregressive sequence probability. The model's logits at position i
    predict the NEXT token, so we gather targets shifted by 1. n_predicted
    is len(tokens)-1 (the number of predictions summed).
    """
    idx = torch.tensor([tokens], dtype=torch.long, device=device)
    inputs = idx[:, :-1]     # positions 0..T-2
    targets = idx[:, 1:]     # positions 1..T-1  (what each position predicts)
    logits, _ = model(inputs, None)
    log_probs = F.log_softmax(logits, dim=-1)
    gathered = log_probs.gather(-1, targets.unsqueeze(-1)).squeeze(-1)
    return float(gathered.sum().item()), int(gathered.numel())


def membership_report(model: TinyGPT, rng: random.Random, device: torch.device,
                      n_per_class: int = 20) -> Dict[str, Tuple[float, List[str]]]:
    """Return {class_name: (mean_per_token_logprob, [sample_decodings])}.

    Mean is per-token (total ll / number of predicted tokens) so short and
    long expressions are comparable — otherwise short counter-examples like
    "5 - 591 = 586" would trivially score higher than long positives purely
    because they sum fewer (negative) terms.
    """
    model.eval()
    results: Dict[str, Tuple[float, List[str]]] = {}
    with torch.no_grad():
        for name, factory in FACTORIES.items():
            per_token: List[float] = []
            samples: List[str] = []
            for _ in range(n_per_class):
                expr = factory(rng)
                total, n = sequence_logprob(model, expr, device)
                per_token.append(total / max(1, n))
                if len(samples) < 2:
                    samples.append(decode(expr))
            results[name] = (sum(per_token) / len(per_token), samples)
    return results


def print_report(report: Dict[str, Tuple[float, List[str]]]) -> None:
    print("\n" + "=" * 72)
    print("MEMBERSHIP TEST  (mean PER-TOKEN log-likelihood; higher = more like generator)")
    print("=" * 72)
    print(f"{'class':<18} {'mean_ll/tok':>12}   sample")
    print("-" * 72)
    for name, (mean_ll, samples) in report.items():
        print(f"{name:<18} {mean_ll:>12.3f}   {samples[0] if samples else ''}")
    print("-" * 72)
    pos_ll = report.get("positive", (0.0, []))[0]
    other_means = [v[0] for k, v in report.items() if k != "positive"]
    other_avg = sum(other_means) / len(other_means) if other_means else 0.0
    print(f"positive mean: {pos_ll:.3f}   others avg: {other_avg:.3f}   "
          f"margin: {pos_ll - other_avg:.3f}")
    print("=" * 72)
