import logging
logging.basicConfig(level=logging.DEBUG)
import asyncio
import os
import sys

# Add framework root to path
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))))

from framework.graph import Graph
from framework.executor.base import Executor
from framework.agents import MockAgent

async def main():
    print("Loading graph from config.json...")
    config_path = os.path.join(os.path.dirname(__file__), "config.json")
    g = Graph.from_json(config_path)
    
    # We use a MockAgent for the demo to save tokens and speed things up,
    # but the HTTP pipelines and web scraping will actually run!
    def mock_llm_response(data, prompt, model, settings):
        if "Filter and return ONLY the threads related to AI" in prompt:
            # We must return a JSON list string matching what the LLM would output
            # For this mock, we just trust the pre-processor which already returned JSON
            return data 
            
        # For the summarizer:
        return f"Mocked LLM Summary for thread:\n```\n{data[:200]}...\n```\n(Summary generated by MockAgent)"
        
    mock_agent = MockAgent(response_fn=mock_llm_response)
    
    print("Executing graph...")
    executor = Executor(g, agents=mock_agent)
    await executor.run()
    
    report_path = os.path.join(os.path.dirname(__file__), "report.md")
    if os.path.exists(report_path):
        print("\n=== SUCCESS: GENERATED REPORT ===")
        with open(report_path, "r", encoding="utf-8") as f:
            print(f.read())
    else:
        print("\nERROR: Report file was not generated.")

if __name__ == "__main__":
    asyncio.run(main())
